# Generated by Django 4.1.7 on 2023-03-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hostel',
            options={'ordering': ('name',), 'verbose_name': 'hostel', 'verbose_name_plural': 'hostels'},
        ),
        migrations.AlterModelOptions(
            name='towns',
            options={'ordering': ('name',), 'verbose_name': 'towns', 'verbose_name_plural': 'townss'},
        ),
    ]
