# Generated by Django 4.1.7 on 2023-03-23 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myhostel', '0003_alter_hostel_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=250, null=True)),
                ('phonenumber', models.CharField(max_length=250, null=True, unique=True)),
                ('medicalnumber', models.CharField(max_length=100, null=True, unique=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('course', models.IntegerField(null=True)),
                ('parentname', models.CharField(max_length=70, null=True)),
                ('parentlastname', models.CharField(max_length=70, null=True)),
                ('parentsurname', models.CharField(max_length=70, null=True)),
                ('parentnumber', models.CharField(max_length=70, null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
