# Generated by Django 4.1.7 on 2023-03-23 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myhostel', '0004_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myhostel.hostel'),
        ),
        migrations.AlterField(
            model_name='students',
            name='medicalnumber',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='parentnumber',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
